<?php

    require_once(dirname(__FILE__) . '/lib/challonge.php');
    ChallongeAPI::$api_key = variable_get('challonge_api_key', '');

    function helper_add_tournament($name, $type, $url, $optional = array())
    {
        $tournament = new ChallongeTournament(); 

        $tournament_params = array();
        $tournament_params['tournament'] = $optional;
        $tournament_params['tournament']['name'] = $name;    
        $tournament_params['tournament']['type'] = $type;    
        $tournament_params['tournament']['url'] = $url;    

        $tournament->setParams($tournament_params);
        return $tournament->reqCreate();
    }

    function helper_edit_tournament($tournament_id, $name, $type, $url, $optional = array())
    {
        $tournament = new ChallongeTournament(); 

        $tournament_params = array();
        $tournament_params['tournament'] = $optional;
        $tournament_params['tournament']['name'] = $name;    
        $tournament_params['tournament']['type'] = $type;    
        $tournament_params['tournament']['url'] = $url;    

        $tournament->setParams($tournament_params);
        return $tournament->reqUpdate($tournament_id);
    }

    /**
     * Creates a participant on challonge using the user's sc2 character name.
     */
    function helper_add_participant($tournament_id, $uid, $seed_number = NULL)
    {
        $user = user_load($uid);
        $char_name_field = variable_get("challonge_profile_name_field", "name");
        $participant_params = array();
        $participant_params['participant']['name'] = $user->$char_name_field; 
        if($seed_number != NULL){
            $participant_params['participant']['seed'] = $seed_number;
        }
        $participant = new ChallongeParticipant($tournament_id);
        $participant->setParams($participant_params);
        return $participant->reqCreate();
    }

    function helper_update_cache()
    {
    }

   
    /**
     *Displays all the tournaments
     */ 
    function challonge_tournament_index()
    {
        //Get all the tournaments.
    }

    /**
     * Implementation of hook_perm
     */
    function challonge_perm()
    {
        return array('administer challonge');
    }

    /**
     * Implementation of hook_menu
     */
    function challonge_menu()
    {
        return array(
            'admin/settings/challonge' => array(
                'title' => t('Challonge'),
                'description' => t('Adjust the settings for the Challonge module.'),
                'file' => 'challonge.admin.inc',
                'page callback' => 'drupal_get_form',
                'page arguments' => array('challonge_settings_form'),
                'access arguments' => array('administer challonge'),
                'type' => MENU_NORMAL_ITEM
            )
        );
    }

    /**
     * Implementation of hook_node_info
     */
    function challonge_node_info()
    {
        return array(
            'tournament' => array(
                'name' => t('Challonge Tournament'),
                'module' => 'challonge',
                'description' => t('A tournament for Challonge.'),
                'help' => t('A tournament for Challonge.')
            )
        );
    }

    /**
     * Implementation of hook_load
     */
    function challonge_load($node)
    {
        $additions = db_fetch_object(db_query("SELECT tournament_id, type AS tournament_type, url AS challonge_url, subdomain FROM {challonge_tournament} WHERE nid = %d", $node->nid));
        return $additions;
    }

    function challonge_init_tournament_params($node)
    {
        $params = array();
        if (strlen($node->subdomain) > 0)
        {
            $params['subdomain'] = $node->subdomain;
        }
        if(strlen($node->description) > 0)
        {
            $params['description'] = $node->description;
        }
        return $params;
    }

    /**
     * Implementation of hook_insert
     */
    function challonge_insert($node)
    {
        $params = challonge_init_tournament_params($node);
        $xml = helper_add_tournament($node->title, $node->tournament_type, $node->challonge_url, $params);
        if ($xml->error)
        {
            drupal_set_message(t('Error adding to Challonge: @error', array('@error' => $xml->error)));
        }
        else
        {
            db_query("INSERT INTO {challonge_tournament} (nid, tournament_id, type, url, subdomain) VALUES (%d, %d, '%s', '%s', '%s')", $node->nid, $xml->id, $node->tournament_type, $node->challonge_url, $node->subdomain);
        }
    }

    /**
     * Implementation of hook_update
     */
    function challonge_update($node)
    {
        if ($tournament_id = db_result(db_query("SELECT tournament_id FROM {challonge_tournament} WHERE nid = %d", $node->nid)))
        {
            $params = challonge_init_tournament_params($node);
            $xml = helper_edit_tournament($tournament_id, $node->title, $node->tournament_type, $node->challonge_url, $params);
            if ($xml->error)
            {
                drupal_set_message(t('Error updating to Challonge: @error', array('@error' => $xml->error)));
            }
            else
            {
                db_query("UPDATE {challonge_tournament} SET tournament_id = %d, type = '%s', url = '%s', subdomain = '%s' WHERE nid = %d", $xml->id, $node->tournament_type, $node->challonge_url, $node->subdomain, $node->nid);
            }
        }
        else
        {
            challonge_insert($node);
        }
    }

    /**
     * Implementation of hook_form
     */
    function challonge_form(&$node, $form_state)
    {
        return array(
            'title' => array(
                '#type' => 'textfield',
                '#title' => t('Name'),
                '#default_value' => $node->title,
                '#required' => true
            ),
            'body' => array(
                '#type' => 'textarea',
                '#title' => t('Description'),
                '#default_value' => $node->body,
                '#rows' => 10,
                '#required' => true
            ),
            'tournament_type' => array(
                '#type' => 'select',
                '#title' => t('Tournament Type'),
                '#default_value' => $node->tournament_type,
                '#options' => array(
                    'single elimination' => t('Single Elimination'),
                    'double elimination' => t('Double Elimination'),
                    'swiss' => t('Swiss'),
                    'round robin' => t('Round Robin')
                ),
                '#required' => true
            ),
            'challonge_url' => array(
                '#type' => 'textfield',
                '#title' => t('Challonge URL'),
                '#default_value' => $node->challonge_url,
                '#required' => true
            ),
            'subdomain' => array(
                '#type' => 'textfield',
                '#title' => t('Challonge Subdomain'),
                '#default_value' => $node->subdomain,
                '#required' => false
            )
        );
    }

    /**
     * Implementation of hook_validate
     */
    function challonge_validate($node, &$form)
    {
        // TODO: Make sure it will not cause a duplicate url/subdomain.
        if (!preg_match('/^[a-zA-Z0-9_]+$/', $node->challonge_url))
        {
            form_set_error('challonge_url', t('The url must only contain letters, numbers and underscores.'));
        }
    }

